openapi: 3.0.0

info:
  title: openapi_practice_api
  description: 櫻井のopenapi_practice
  version: 1.0.0

servers:
  - url: https://localhost/api/v1


paths:
  /posts:
    get:
      summary: 投稿一覧の取得
      operationId: getPosts
      responses:
        '200':
          description: 成功
          content:
            application/json:
              schema:
                type: object
                required:
                  - message
                  - data
                properties:
                  message:
                    type: string
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Post'
                additionalProperties: false
components:
  schemas:
    Post:
      type: object
      required:
        - id
        - title
      properties:
        id:
          type: integer
        title:
          type: string
